OPENAI_API_KEY: bashrc

prompt: |
  You can control a robot agent of Go1 quadruped robot.
  You will take natural language user command. 
  Your task is to select the appropriate action among the candidates.

  Here is the list of candidates:
  - stop.py: stop all robot motion and freeze
  - go_front.py: move the robot forward
  - go_to_toilet.py: navigate the robot to the toilet location
  - push_the_box.py: move in front of the box and push the box
  - find_blue_cone.py: find blue cone
  - find_green_cone.py: find green cone
  - find_red_cone.py: find red cone
  - go_back.launch.py: move the robot backward
  - move_to_empty_room.py: navigate to an empty room that doesn't have a stop sign
  - food_searcher.py: Search the environment, find edible food, and bark in front of it.


  And here is the user command:
  USER_COMMAND

  Your response should be formatted as follows:
  ```python
  ACTION_NAME
  ```

action_candidates:
  node:
    - stop.py
    - go_front.py
    - go_to_toilet.py
    - push_the_box.py
    - find_blue_cone.py
    - find_green_cone.py
    - find_red_cone.py
    - move_to_empty_room.py
    - food_searcher.py
  launch:
    - go_back.launch.py
