OPENAI_API_KEY: bashrc

prompt: |
  You can control a robot agent of Go1 quadruped robot.
  You will take natural language user command. 
  Your task is to select the appropriate action among the candidates.

  Here is the list of candidates:
  - stop.py: stop all robot motion and freeze
  - go_front.py: move the robot forward
  - go_to_toilet.py: navigate the robot to the toilet location
  - go_back.launch.py: move the robot backward

  And here is the user command:
  USER_COMMAND

  Your response should be formatted as follows:
  ```python
  ACTION_NAME
  ```

action_candidates:
  node:
    - stop.py
    - go_front.py
    - go_to_toilet.py
  launch:
    - go_back.launch.py